import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AudioLines, CameraOff, HeartPulse, Waves } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import { supabase } from '../../lib/supabaseClient'
import { generateRecording } from '../../lib/mockDataGenerator'

const READING_PHRASE =
  'The early morning light stretched slowly across the quiet valley, while a distant train rolled steadily toward the horizon, its low whistle echoing between the hills as birds began to stir among the trees.'

const SCAN_SECONDS = 30

type Phase = 'idle' | 'recording' | 'processing' | 'saving' | 'error'

const PROCESSING_MESSAGES = [
  'Processing facial blood flow…',
  'Analyzing audio spectrogram…',
  'Estimating pulse-wave shape…',
  'Cross-checking rhythm irregularities…',
]

export function RecordingSession() {
  const { profile } = useAuth()
  const navigate = useNavigate()
  const videoRef = useRef<HTMLVideoElement | null>(null)
  const streamRef = useRef<MediaStream | null>(null)

  const [phase, setPhase] = useState<Phase>('idle')
  const [secondsLeft, setSecondsLeft] = useState(SCAN_SECONDS)
  const [cameraAvailable, setCameraAvailable] = useState(true)
  const [processingMessageIndex, setProcessingMessageIndex] = useState(0)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)

  useEffect(() => {
    return () => {
      streamRef.current?.getTracks().forEach((track) => track.stop())
    }
  }, [])

  async function startScan() {
    setErrorMessage(null)
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true })
      streamRef.current = stream
      if (videoRef.current) {
        videoRef.current.srcObject = stream
        await videoRef.current.play().catch(() => {})
      }
      setCameraAvailable(true)
    } catch {
      // It just shows a placeholder instead of a live feed.
      setCameraAvailable(false)
    }
    setPhase('recording')
  }

  useEffect(() => {
    if (phase !== 'recording') return

    if (secondsLeft <= 0) {
      streamRef.current?.getTracks().forEach((track) => track.stop())
      setPhase('processing')
      return
    }

    const timer = setTimeout(() => setSecondsLeft((s) => s - 1), 1000)
    return () => clearTimeout(timer)
  }, [phase, secondsLeft])

  useEffect(() => {
    if (phase !== 'processing') return

    const interval = setInterval(() => {
      setProcessingMessageIndex((i) => (i + 1) % PROCESSING_MESSAGES.length)
    }, 900)

    const timeout = setTimeout(async () => {
      clearInterval(interval)
      setPhase('saving')
      await saveRecording()
    }, PROCESSING_MESSAGES.length * 900 + 400)

    return () => {
      clearInterval(interval)
      clearTimeout(timeout)
    }
  }, [phase])

  async function saveRecording() {
    if (!profile) return
    const metrics = generateRecording()

    const { data, error } = await supabase
      .from('recordings')
      .insert({
        patient_id: profile.id,
        overall_risk_tier: metrics.overallTier,
        metrics,
      })
      .select('id')
      .single()

    if (error || !data) {
      setPhase('error')
      setErrorMessage(error?.message ?? 'Could not save this scan. Please try again.')
      return
    }

    navigate(`/patient/report/${data.id}`)
  }

  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
      <h1 className="font-display text-2xl sm:text-3xl font-semibold text-ink text-center mb-2">
        Simulated scan
      </h1>
      <p className="text-ink-soft text-center mb-8">
        Every result on the next screen is generated by a mock data engine — nothing
        here is a real medical measurement.
      </p>

      <div className="bg-ink rounded-2xl overflow-hidden aspect-video relative flex items-center justify-center">
        {phase !== 'idle' && cameraAvailable ? (
          <video ref={videoRef} muted playsInline className="w-full h-full object-cover" />
        ) : (
          <div className="text-paper/60 flex flex-col items-center gap-3">
            <CameraOff size={36} aria-hidden="true" />
            <span className="text-sm">
              {phase === 'idle' ? 'Camera preview will appear here' : 'Camera unavailable — continuing in simulation mode'}
            </span>
          </div>
        )}

        {phase === 'recording' && (
          <div className="absolute inset-0 bg-ink/40 flex flex-col items-center justify-center text-paper p-6 text-center">
            <p className="font-mono text-4xl font-semibold mb-4">{secondsLeft}s</p>
            <p className="max-w-md text-sm sm:text-base leading-relaxed">
              &ldquo;{READING_PHRASE}&rdquo;
            </p>
          </div>
        )}

        {(phase === 'processing' || phase === 'saving') && (
          <div className="absolute inset-0 bg-ink/70 flex flex-col items-center justify-center text-paper gap-4">
            <HeartPulse size={32} className="text-coral animate-pulse" aria-hidden="true" />
            <p className="font-mono text-sm tracking-wide">
              {phase === 'saving' ? 'Preparing your report…' : PROCESSING_MESSAGES[processingMessageIndex]}
            </p>
          </div>
        )}
      </div>

      {phase === 'idle' && (
        <button
          onClick={startScan}
          className="mt-8 w-full bg-coral text-paper font-semibold rounded-full py-3.5 hover:opacity-90 transition-opacity flex items-center justify-center gap-2"
        >
          <Waves size={18} aria-hidden="true" />
          Begin 30-second scan
        </button>
      )}

      {phase === 'recording' && (
        <p className="mt-6 flex items-center justify-center gap-2 text-sm text-ink-soft">
          <AudioLines size={16} aria-hidden="true" />
          Keep reading at a natural pace — the scan ends automatically.
        </p>
      )}

      {phase === 'error' && (
        <div className="mt-6 text-center">
          <p className="text-alert bg-alert-soft rounded-lg px-4 py-3 text-sm mb-4">
            {errorMessage}
          </p>
          <button
            onClick={() => {
              setPhase('idle')
              setSecondsLeft(SCAN_SECONDS)
            }}
            className="text-teal font-medium hover:underline text-sm"
          >
            Try again
          </button>
        </div>
      )}
    </div>
  )
}
