import { Link } from 'react-router-dom'
import { Activity, Mic, ScanFace, Stethoscope, UserRound } from 'lucide-react'
import { HeartbeatRule } from '../components/HeartbeatRule'

const STEPS = [
  {
    icon: ScanFace,
    title: '1. Look and read',
    body: 'Sit facing your camera and read a short sentence aloud for 30 seconds, while the app watches subtle color shifts in your face and listens to your voice.',
  },
  {
    icon: Activity,
    title: '2. Simulated processing',
    body: 'A processing animation walks through what a real facial-blood-flow and audio-spectrogram analysis pipeline would do, step by step.',
  },
  {
    icon: Stethoscope,
    title: '3. Review your report',
    body: 'You get a simulated report: a heart-rate trace, an audio-sync score, and plain-language next steps you can act on today.',
  },
]

export function Landing() {
  return (
    <div>
      {/* Hero */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 pt-16 sm:pt-24 pb-10">
        <div className="max-w-2xl">
          <p className="font-mono text-xs tracking-widest uppercase text-teal mb-4">
            Simulated pre-screening demo
          </p>
          <h1 className="font-display text-4xl sm:text-5xl font-semibold leading-tight text-ink">
            Look into your camera. Read a sentence. See your heart&rsquo;s rhythm.
          </h1>
          <p className="mt-5 text-lg text-ink-soft leading-relaxed">
            CardiologistAI is an open-source prototype of a remote cardiovascular
            pre-screening experience, built with a phone or laptop camera and
            microphone in mind. Every reading is generated by a mock data engine, not
            a real analysis — it exists to demonstrate the product idea, not to screen
            anyone&rsquo;s heart.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row gap-3">
            <Link
              to="/signup"
              className="inline-flex items-center justify-center gap-2 bg-coral text-paper px-6 py-3 rounded-full font-semibold hover:opacity-90 transition-opacity"
            >
              <UserRound size={18} aria-hidden="true" />
              I&rsquo;m a patient
            </Link>
            <Link
              to="/signup"
              className="inline-flex items-center justify-center gap-2 bg-teal-soft text-teal-deep px-6 py-3 rounded-full font-semibold hover:bg-teal hover:text-paper transition-colors"
            >
              <Stethoscope size={18} aria-hidden="true" />
              I&rsquo;m a doctor
            </Link>
          </div>
        </div>
      </section>

      <HeartbeatRule />

      {/* How it works */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 py-16 sm:py-20">
        <h2 className="font-display text-2xl sm:text-3xl font-semibold text-ink mb-10">
          How a scan works
        </h2>
        <div className="grid sm:grid-cols-3 gap-8">
          {STEPS.map((step) => (
            <div key={step.title}>
              <div className="w-11 h-11 rounded-full bg-teal-soft flex items-center justify-center mb-4">
                <step.icon size={20} className="text-teal-deep" aria-hidden="true" />
              </div>
              <h3 className="font-display text-lg font-semibold text-ink mb-2">{step.title}</h3>
              <p className="text-ink-soft leading-relaxed">{step.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Concept explainer */}
      <section className="bg-teal-soft/60 py-16 sm:py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 grid md:grid-cols-2 gap-10 items-start">
          <div>
            <h2 className="font-display text-2xl sm:text-3xl font-semibold text-ink mb-4">
              The idea behind rPPG and voice analysis
            </h2>
            <p className="text-ink-soft leading-relaxed mb-4">
              Remote photoplethysmography (rPPG) is a real research technique that
              estimates blood-flow changes from tiny color shifts in facial skin,
              captured on ordinary video. Paired with audio analysis of a person&rsquo;s
              speech, it&rsquo;s an active area of digital-health research aimed at
              lightweight, camera-only heart screening.
            </p>
            <p className="text-ink-soft leading-relaxed">
              This project simulates what a product built on that idea could feel
              like — the recording flow, the report, the doctor&rsquo;s view — using a
              mock data generator instead of a working rPPG pipeline. Treat every
              number you see here as a placeholder for what real signal processing
              might one day produce, not as a working measurement.
            </p>
          </div>
          <div className="bg-paper rounded-2xl border border-ink/10 p-6 sm:p-8">
            <div className="flex items-center gap-2 text-teal-deep font-semibold mb-4">
              <Mic size={18} aria-hidden="true" />
              What the recording screen watches for
            </div>
            <ul className="space-y-3 text-sm text-ink-soft">
              <li>· Simulated facial blood-flow trace, sampled over 30 seconds</li>
              <li>· Simulated audio-cadence sync score from your reading voice</li>
              <li>· Mock atrial fibrillation and heart-failure pre-screening patterns</li>
              <li>· A simulated pulse-wave analysis graph</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="max-w-6xl mx-auto px-4 sm:px-6 py-12 text-sm text-ink-soft">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <p>
            CardiologistAI is a free, open-source educational portfolio project. It
            contains no payment features and performs no real medical diagnosis.
          </p>
          <p className="font-mono text-xs">Built for demonstration purposes only.</p>
        </div>
      </footer>
    </div>
  )
}
